[container.image]
repository="ramilu90" # Docker hub repository name.
name="airline-service" # container name
tag="latest"

[[cloud.config.envs]]
key_ref="MOCK_API_BASE_URL"
config_name="ballerina-values"

# [[cloud.config.envs]]
# key_ref="BAL_CONFIG_VAR_BALLERINAX_WSO2_APIM_CATALOG_SERVICEURL"
# config_name="ballerina-values"

# [[cloud.config.envs]]
# key_ref="BAL_CONFIG_VAR_BALLERINAX_WSO2_APIM_CATALOG_TOKENURL"
# config_name="ballerina-values"

# [[cloud.secret.envs]]
# key_ref="BAL_CONFIG_VAR_BALLERINAX_WSO2_APIM_CATALOG_USERNAME"
# secret_name="ballerina-secrets"

# [[cloud.secret.envs]]
# key_ref="BAL_CONFIG_VAR_BALLERINAX_WSO2_APIM_CATALOG_PASSWORD"
# secret_name="ballerina-secrets"

# [[cloud.secret.envs]]
# key_ref="BAL_CONFIG_VAR_BALLERINAX_WSO2_APIM_CATALOG_CLIENTID"
# secret_name="ballerina-secrets"

# [[cloud.secret.envs]]
# key_ref="BAL_CONFIG_VAR_BALLERINAX_WSO2_APIM_CATALOG_CLIENTSECRET"
# secret_name="ballerina-secrets"

[[cloud.config.envs]]
key_ref="BAL_CONFIG_DATA"
config_name="ballerina-values"

[[cloud.config.envs]]
key_ref="BAL_CONFIG_VAR_BALLERINA_HTTP_TRACELOGCONSOLE"
config_name="ballerina-values"
# [[cloud.config.envs]]
# key_ref="BAL_CONFIG_VAR_BALLERINAX_WSO2_CONTROLPLANE_DASHBOARD_URL"
# config_name="ballerina-values"

# [[cloud.config.envs]]
# key_ref="BAL_CONFIG_VAR_BALLERINAX_WSO2_CONTROLPLANE_DASHBOARD_HEARTBEATINTERVAL"
# config_name="ballerina-values"

# [[cloud.config.envs]]
# key_ref="BAL_CONFIG_VAR_BALLERINAX_WSO2_CONTROLPLANE_DASHBOARD_GROUPID"
# config_name="ballerina-values"

# [[cloud.config.envs]]
# key_ref="BAL_CONFIG_VAR_BALLERINAX_WSO2_CONTROLPLANE_DASHBOARD_MGTAPIURL"
# config_name="ballerina-values"

# [[cloud.config.envs]]
# key_ref="BAL_CONFIG_VAR_BALLERINAX_WSO2_CONTROLPLANE_DASHBOARD_NODEID"
# config_name="ballerina-values"
