[package]
org = "ramindu"
name = "fto_to_nfs_file_transfer"
version = "0.1.0"
title = "fto_to_nfs_file_transfer"

[build-options]
sticky = true

[[platform.java17.dependency]]
groupId = "com.mysql"
artifactId = "mysql-connector-j"
version = "8.3.0"