[container.image]
repository="ramilu90" # Docker hub repository name.
name="mock_backend" # container name
tag="1.0.2"

[[cloud.config.envs]]
key_ref="BAL_CONFIG_DATA"
config_name="ballerina-values-mock-backends"

[[cloud.config.envs]]
key_ref="BAL_CONFIG_VAR_BALLERINA_HTTP_TRACELOGCONSOLE"
config_name="ballerina-values-mock-backends"