[package]
org = "ramindu"
name = "orchestration_and_email_sms"
version = "0.1.0"
title = "orchestration_and_email_sms"

[build-options]
cloud = "k8s"
remoteManagement=true
sticky = true
observabilityIncluded=true