[container.image]
repository="ramilu90" # Docker hub repository name.
name="orchestration_and_email_sms" # container name
tag="1.0.0"

[[cloud.secret.envs]]
key_ref="smtpUsername"
secret_name="ballerina-secrets"

[[cloud.secret.envs]]
key_ref="smtpPassword"
secret_name="ballerina-secrets"

[[cloud.secret.envs]]
key_ref="twilioAccountSid"
secret_name="ballerina-secrets"

[[cloud.secret.envs]]
key_ref="twilioAuthToken"
secret_name="ballerina-secrets"

[[cloud.config.envs]]
key_ref="smtpHost"
config_name="ballerina-values"

[[cloud.config.envs]]
key_ref="smtpPortStr"
config_name="ballerina-values"

[[cloud.config.envs]]
key_ref="emailFrom"
config_name="ballerina-values"

[[cloud.config.envs]]
key_ref="emailTo"
config_name="ballerina-values"

[[cloud.config.envs]]
key_ref="twilioFromNumber"
config_name="ballerina-values"

[[cloud.config.envs]]
key_ref="twilioToNumber"
config_name="ballerina-values"

[[cloud.config.envs]]
key_ref="smtpUsername"
config_name="ballerina-values"

[[cloud.config.envs]]
key_ref="oasUrl"
config_name="ballerina-values"

[[cloud.config.envs]]
key_ref="cashRegistryUrl"
config_name="ballerina-values"

[[cloud.config.envs]]
key_ref="notificationUrl"
config_name="ballerina-values"