[container.image]
repository="ramilu90" # Docker hub repository name.
name="sf-to-servicenow" # container name
tag="latest"

[[cloud.secret.envs]]
key_ref="servicenowUsername"
secret_name="ballerina-secrets"

[[cloud.secret.envs]]
key_ref="servicenowPassword"
secret_name="ballerina-secrets"

[[cloud.secret.envs]]
key_ref="salesforceClientId"
secret_name="ballerina-secrets"

[[cloud.secret.envs]]
key_ref="salesforceClientSecret"
secret_name="ballerina-secrets"

[[cloud.secret.envs]]
key_ref="pineconeApiKey"
secret_name="ballerina-secrets"

[[cloud.secret.envs]]
key_ref="sendgridApiToken"
secret_name="ballerina-secrets"

[[cloud.secret.envs]]
key_ref="sendGridSenderEmail"
secret_name="ballerina-secrets"

[[cloud.secret.envs]]
key_ref="openaiApiKey"
secret_name="ballerina-secrets"

[[cloud.secret.envs]]
key_ref="cloudmersiveApiKey"
secret_name="ballerina-secrets"

[[cloud.config.envs]]
key_ref="pineconeVectorStoreUrl"
config_name="ballerina-values"

[[cloud.config.envs]]
key_ref="salesforceTokenUrl"
config_name="ballerina-values"

[[cloud.config.envs]]
key_ref="salesforceBaseUrl"
config_name="ballerina-values"

[[cloud.config.envs]]
key_ref="servicenowBaseUrl"
config_name="ballerina-values"

[[cloud.config.envs]]
key_ref="BAL_CONFIG_DATA"
config_name="ballerina-values-sf-to-serviceno"