[package]
org = "ramindu"
name = "salesforce_to_sap"
version = "0.3.0"
distribution = "2201.12.7"

[[dependency]]
org = "ballerina"
name = "http"
version = "2.15.0"

[build-options]
cloud = "k8s"
# cloud = "docker"

