apiVersion: v1
kind: ConfigMap
metadata:
  # This is the name you will reference in your Deployment/Pod
  name: ballerina-values-vies
data:
  # The key-value pair that holds your URL
  BAL_CONFIG_VAR_BALLERINAX_WSO2_CONTROLPLANE_NODEID: "sf-to-vies"
  BAL_CONFIG_DATA: ' [ballerinax.wso2.controlplane.dashboard] \n url="https://cloud-wso2-icp.icp.svc.cluster.local:9743/dashboard/api" \n heartbeatInterval=10 \n groupId="cluster1" \n mgtApiUrl="https://vies-integratio.ballerina.svc.cluster.local:9264/management/" \n nodeId="vies" '
