[package]
org = "ramindu"
name = "vies_integration"
version = "0.1.0"

[build-options]
cloud = "k8s"

[[dependency]]
org = "ballerina"
name = "http"
version = "2.15.2"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.10.0"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.8.0"

[[dependency]]
org = "ballerina"
name = "io"
version = "1.8.0"

[[dependency]]
org = "ballerina"
name = "os"
version = "1.7.0"