[container.image]
repository="ramilu90" # Docker hub repository name.
name="vies_integration" # container name
tag="latest"

# [[cloud.config.envs]]
# key_ref="MOCK_API_BASE_URL"
# config_name="ballerina-values"

# [settings]
# buildImage=true


[[cloud.config.envs]]
key_ref="viesServiceUrl"
config_name="ballerina-values"

[[cloud.config.envs]]
key_ref="BAL_CONFIG_DATA"
config_name="ballerina-values-vies"